---
version: 3
includes:
  git:
    taskfile: git/git.yaml
  lint:
    taskfile: git/linting.yaml

tasks:
  default:
    desc: Default task is select & do (work)
    cmds:
      - task do

  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | \
          sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"
